Repository MicrosoftDocs/dynamics-365-unified-operations-public, pull requests merged in 2018-06, with the labels that each got.

#111 Update to drop stored procs used by DMF
  articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md
Labels: assigned-to-author

#110 Update to drop stored procs used by DMF
  articles/dev-itpro/database/copy-database-from-sql-server-to-azure-sql.md
Labels: assigned-to-author

#191 Update add-enum-value.md
  articles/dev-itpro/extensibility/add-enum-value.md
Labels: doc-enhancement

#140 Update retail-sdk-packaging.md
  articles/retail/dev-itpro/retail-sdk/retail-sdk-packaging.md
Labels: doc-enhancement, triaged, vsts

#142 Add a link to the blog post
  articles/financials/general-ledger/financial-dimensions.md
Labels: assigned-to-author, doc-enhancement, triaged

#141 Add a link to the overview post
  articles/financials/general-ledger/general-ledger.md
Labels: assigned-to-author, doc-enhancement, triaged

#160 Update prerequisites-standard-costs.md
  articles/supply-chain/cost-management/prerequisites-standard-costs.md
Labels: assigned-to-author, bug-created-VSTS, doc-bug, triaged
