Repository MicrosoftDocs/dynamics-365-unified-operations-public, pull requests merged in 2018-12, with the labels that each got.

#626 Update order-attributes.md
  articles/retail/dev-itpro/order-attributes.md
Labels: in-progress

#676 Updating the usage of self signed certificates
  articles/dev-itpro/deployment/warehousing-for-on-premise-deployments.md
Labels: triaged

#684 Update data-entities-data-packages.md
  articles/dev-itpro/data-entities/data-entities-data-packages.md
Labels: resolves-docs-issue

#685 Update services-home-page.md
  articles/dev-itpro/data-entities/services-home-page.md
Labels: resolves-docs-issue

#681 Update export-entities-to-your-own-database.md
  articles/dev-itpro/analytics/export-entities-to-your-own-database.md
Labels: resolves-docs-issue
